### Health
GET http://localhost:8000/health


### LIST tasks
GET http://localhost:8000/tasks?page=0&size=3&order_by=created_at



### CREATE task
POST http://localhost:8000/tasks
Content-Type: application/json

{
    "title": "Task 3",
    "description": "Task 3 description"
}
