### Health
GET http://localhost:8000/health


### LIST tasks
GET http://localhost:8000/tasks?page=0&size=3&order_by=created_at
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJiOGYwN2YyZS00NDBjLTRhZDMtOGRmNi0wOTYzMjVhNTUwN2YiLCJleHAiOjE3NTczMDczMTJ9.GaW_-SsVRzRSgKL6Em8PFW4J6eWLgc0pMveu0V6c46w


### CREATE task
POST http://localhost:8000/tasks
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJiOGYwN2YyZS00NDBjLTRhZDMtOGRmNi0wOTYzMjVhNTUwN2YiLCJleHAiOjE3NTczMDY1MDJ9.VOUrRhzhv8ZZB6A1y1z99a3K_6LREirKVCI-EOZic4g

{
    "title": "Task 3",
    "description": "Task 3 description"
}


### GET task
GET http://localhost:8000/tasks/2aa42f2f-79e1-4a29-bba0-6dc2d76c0dcb


### DELETE task
DELETE http://localhost:8000/tasks/2aa42f2f-79e1-4a29-bba0-6dc2d76c0dcc


### UPDATE task
PUT http://localhost:8000/tasks/08158174-286b-45d3-8b97-ced53baa5ec4
Content-Type: application/json

{
    "title": "Task 5"
}


### Signup
POST http://localhost:8000/auth/signup
Content-Type: application/json

{
    "username": "test2",
    "password": "test"
}


### Login
POST http://localhost:8000/auth/login
Content-Type: application/json

{
    "username": "test",
    "password": "test"
}
