### LIST tasks
GET http://localhost:8000/tasks?page=0&size=3&order_by=created_at
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI3OWFjOTIzMC1hMjkxLTQ0NGItYmVkOC05ZWJlMGM2ZWQwZDgiLCJleHAiOjE3NTczOTAyNjZ9.PKEdiHC8q3dYNeDKUd4EJWjYMlbBK48eMGr10dGQnCc


### CREATE task
POST http://localhost:8000/tasks
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI3OWFjOTIzMC1hMjkxLTQ0NGItYmVkOC05ZWJlMGM2ZWQwZDgiLCJleHAiOjE3NTczOTAyNjZ9.PKEdiHC8q3dYNeDKUd4EJWjYMlbBK48eMGr10dGQnCc

{
    "title": "Task 1",
    "description": "Task 1 description",
    "status": "PENDING"
}


### GET task
GET http://localhost:8000/tasks/59dc56d4-2ab3-41d8-95f7-4d724b19bd59
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI3OWFjOTIzMC1hMjkxLTQ0NGItYmVkOC05ZWJlMGM2ZWQwZDgiLCJleHAiOjE3NTczOTAyNjZ9.PKEdiHC8q3dYNeDKUd4EJWjYMlbBK48eMGr10dGQnCc


### DELETE task
DELETE http://localhost:8000/tasks/84a2b21c-f314-4404-92cc-b2fabe203129
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI3OWFjOTIzMC1hMjkxLTQ0NGItYmVkOC05ZWJlMGM2ZWQwZDgiLCJleHAiOjE3NTczOTAyNjZ9.PKEdiHC8q3dYNeDKUd4EJWjYMlbBK48eMGr10dGQnCc


### UPDATE task
PUT http://localhost:8000/tasks/59dc56d4-2ab3-41d8-95f7-4d724b19bd59
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI3OWFjOTIzMC1hMjkxLTQ0NGItYmVkOC05ZWJlMGM2ZWQwZDgiLCJleHAiOjE3NTczOTAyNjZ9.PKEdiHC8q3dYNeDKUd4EJWjYMlbBK48eMGr10dGQnCc
Content-Type: application/json

{
    "title": "Task update"
}


### Signup
POST http://localhost:8000/auth/signup
Content-Type: application/json

{
    "username": "test",
    "password": "test"
}


### Login
POST http://localhost:8000/auth/login
Content-Type: application/json

{
    "username": "test",
    "password": "test"
}
