"""add relations beatween task and user

Revision ID: dcc07d841c21
Revises: 77e70fd0f7cd
Create Date: 2025-09-08 00:05:59.621731

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "dcc07d841c21"
down_revision: Union[str, Sequence[str], None] = "77e70fd0f7cd"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("task", sa.Column("user_id", sa.UUID(), nullable=False))
    op.create_foreign_key(None, "task", "user", ["user_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "task", type_="foreignkey")
    op.drop_column("task", "user_id")
    # ### end Alembic commands ###
