"""add status to task

Revision ID: e5052a8e42e0
Revises: dcc07d841c21
Create Date: 2025-09-08 22:09:46.986140

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "e5052a8e42e0"
down_revision: Union[str, Sequence[str], None] = "dcc07d841c21"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("task", sa.Column("status", sa.String(length=100), nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("task", "status")
    # ### end Alembic commands ###
